### ISSUE TITLE
markdown-unlit belongs into build-tools, not build-depends

### ISSUE THREAD

**Issue by peti** [sol/markdown-unlit#1]
The readme example declares markdown-unlit as a required library:

    test-suite readme
      type:           exitcode-stdio-1.0
      main-is:        README.lhs
      build-depends:  base, markdown-unlit
      ghc-options:    -pgmL markdown-unlit

In fact, however, it is a `build-tool`.

**Comment by sol** [comment]
Adding it to `build-depends` works AFAIK, but specifying it as a `build-tool` does not.  Please correct me if I'm wrong on this ;)

**Comment by peti** [comment]
Why would it not work?

**Comment by peti** [comment]
I'm guessing that this `Setup.hs` file is what might be missing?

    module Main ( main ) where

    import Distribution.Simple
    import Distribution.Simple.Program

    main :: IO ()
    main = defaultMainWithHooks simpleUserHooks
           { hookedPrograms = [ simpleProgram "markdown-unlit" ]
           }

**Comment by sol** [comment]
`build-tools` are not automatically installed by `cabal`.  Unless there is a strong case for changing this or somebody can point out a more robust solution, I would go with what we currently have.  This approach is battle tested, we use it for `hspec-discover` too, and I'm not aware of any issues.

(related discussion is here https://github.com/zalora/getopt-generics/issues/23#issuecomment-95988704)

**Comment by sol** [comment]
@peti thanks for the report.  With the current sate of Cabal, `build-depends` is the best we have.  I'm closing this for now.

**Comment by peti** [comment]
This decision causes more problems now. `cabal-rpm` generates spec files for SUSE Linux (and others) that specficy a build-time dependency on `ghc-markdown-unlit-devel`, which is the package containing the library. The executable, however, isn't in there and so the build fails. The assumption that installing the library automatically provides the executable too is false, really, and this should be fixed.

**Comment by turion** [comment]
The correct usage is `build-tool-depends: markdown-unlit`, isn't it?

**Comment by turion** [comment]
(See also https://cabal.readthedocs.io/en/3.4/cabal-package.html?highlight=build-tool-depends#pkg-field-build-tool-depends)
