### ISSUE TITLE
Is there a way to import the code taken from markdown?

### ISSUE THREAD

**Issue by caphesuanong** [sol/markdown-unlit#14]
Is there a way to import the code taken from markdown? I'm trying to import the code so that a test can call it. It would be really helpful to see an example where a main function in markdown was called from within a test. This way the code in my README.md could be tested as part of a test framework.

**Comment by sol** [comment]
Yes, that's possible.  But you have to add a `module ...` in the first code block.  You also can't use `Main` as the module name + you should symlink `README.md` to `MyModule.lhs` (where `MyModule` would be the name that you can import).
