### ISSUE TITLE
How to combine markdown-unlit and doctest?

### ISSUE THREAD

**Issue by elviejo79** [sol/markdown-unlit#15]
So I'm trying to write programming exercises.
One way to go about it is to write the exercise and the instructions as markdown file like

## Instructions for the exercise

Then let the students complete the code

```haskell
module Fib where

-- | Compute Fibonacci numbers
--
-- Examples:
--
-- >>> fib 10
-- 55
--
-- >>> fib 5
-- 5
fib :: Int -> Int
fib 0 = 0
fib 1 = 1
fib n = undefined -- This is what the student would do.
```

I been able to compile the code in the literate haskell (Readme.lhs)

And have also been able to tangle the haskell code only  and run the doctests on it.

However I haven't been able to run the doctests inside a markdown file.

Maybe it's not possible?
Or if it is what would be the appropriate Cabal configuration?
Are there examples of Literate packages, that execute doctests?

**Comment by sol** [comment]
@elviejo79 sorry for the late reply.  Yes, it should be possible.  For your example, if the module is called `Fib.hs` then you would need to symlink the `.md` file to `Fib.lhs`.  You also can only have one `module`-name that is picked up by `markdown-unlit` + the corresponding `module`-statement needs to be at the beginning of the first code block that is picked up by `markdown-unlit`.  Refer to the the README on how to control what is picked up by `markdown-unlit`: https://github.com/sol/markdown-unlit#customizing

**Comment by sol** [comment]
**Example on how to use `markdown-unlit` with `doctest`:**

```markdown
# Instructions

Implement a functions that calculates Fibonacci numbers.

```haskell
-- | Compute Fibonacci numbers
--
-- Examples:
--
-- >>> fib 10
-- 55
--
-- >>> fib 5
-- 5
fib :: Int -> Int
fib 0 = 0
fib 1 = 1
fib n = undefined -- This is what the student would do.
```

```bash
doctest -pgmL markdown-unlit Fib.lhs
Foo.lhs:10: failure in expression `fib 10'
expected: 55
 but got: *** Exception: Prelude.undefined
          ^
          CallStack (from HasCallStack):
            undefined, called at Foo.lhs:18:9 in main:Main

Examples: 2  Tried: 1  Errors: 0  Failures: 1
```
