### ISSUE TITLE
Typecheck only

### ISSUE THREAD

**Issue by domenkozar** [sol/markdown-unlit#54]
In some cases where demonstrating how to run a long-running program,
it isn't feasible to run main, but type-checking would still be enormous value.

**Comment by sol** [comment]
How exactly is this related to `markdown-unlit`, or what exact change are you asking for?

**Comment by domenkozar** [comment]
I'd like the `test-suite` to only type check a README.md, but not execute `main`.

It's related to it's usage, not it's implementation directly.

**Comment by sol** [comment]
You could probably have a regular executable, that you then only build on CI via a flag. Or you could have a test suite, but only build it and never run it.

Overall, I feel this is more of a Cabal issue and not specific to markdown-unlit.

**Comment by domenkozar** [comment]
Thanks, ended up with: https://github.com/cachix/websockets-simple/blob/main/websockets-simple.cabal#L44
