### ISSUE TITLE
Plugin does not work for plain modules

### ISSUE THREAD

**Issue by abailly-iohk** [sol/markdown-unlit#55]
I am trying to use `markdown-unlit` to write some LHS files in Markdown, but I am getting this error on one of the modules:

```
CircularBuffer/Buffer.lhs:1:1: error: [GHC-28623]
    File name does not match module name:
    Saw     : ‘Main’
    Expected: ‘CircularBuffer.Buffer’
  |
1 | > {-# LANGUAGE NamedFieldPuns #-}
  | ^
```

I infer from that error the plugin expects the file to be a `Main` file. Is this expected? Am I doing something wrong?

Here is the relevant section of the cabal file:

```
library
  import:          lang
  hs-source-dirs:  .
  exposed-modules:
      DL
    , CircularBuffer.Model
    , CircularBuffer.Buffer
  build-depends:
    , base        >=4.7 && <5
    , containers
    , markdown-unlit
    , mtl
    , QuickCheck
    , quickcheck-dynamic
    , random
    , vector
  ghc-options:    -pgmL markdown-unlit
  build-tool-depends: markdown-unlit:markdown-unlit
```

**Comment by sol** [comment]
> Am I doing something wrong?

Did you add

    ```haskell
    module CircularBuffer.Buffer where
    ```

at the top of your literate source file?

If this does not resolve your issue, then please provide full steps on how to reproduce.

**Comment by abailly-iohk** [comment]
That helps, but now I have another error when building the `Main` file:

```
app/Main.hs:1:30: error:
    Module ‘CircularBuffer.Model’ does not export ‘prop_CircularBuffer’
  |
1 | import CircularBuffer.Model (prop_CircularBuffer)
  |                              ^^^^^^^^^^^^^^^^^^^
```

`CircularBuffer.Model` now looks like:

````
```haskell
{-# LANGUAGE InstanceSigs #-}
{-# LANGUAGE NamedFieldPuns #-}
module CircularBuffer.Model (prop_CircularBuffer) where
```

prop_CircularBuffer :: Property
... 
````

There's something fishy going on with module's content which is probably unrelated to `markdown-unlit`.

**Comment by sol** [comment]
@abailly-iohk  is there still something I can do here, related to `markdown-unlit`?

**Comment by abailly-iohk** [comment]
@sol Sorry for lack of reactivity! I don't think I went to the bottom of it all, but I also don't think this has anything to do with this tool so I will just close the issue. Thanks for your help.
