### ISSUE TITLE
Error: could not execute markdown-unlit

### ISSUE THREAD

**Issue by michaelgwelch** [sol/markdown-unlit#6]
This looks like a cool project. I was following the quickstart on your README.

However, when I attempt to load the Haskell source into ghci I get an error

```sh
marathon:literateHaskellMarkdown mgwelch$ ghci -pgmL markdown-unlit README.lhs
GHCi, version 8.0.1: http://www.haskell.org/ghc/  :? for help
ghc: could not execute: markdown-unlit
> :quit
Leaving GHCi.
```

Any suggestion?

**Comment by sol** [comment]
Is `markdown-unlit` on your `PATH`?  Maybe `stack exec` or something?

**Comment by sol** [comment]
Or `cabal exec` for that matter...

**Comment by michaelgwelch** [comment]
Yeah, I think it is a path issue. Haven't used cabal in a year. Doesn't that normally install to a directory already in your path? Looks like I need to check my environment.

After installing your library I installed pandoc via cabal and had the same issue: namely couldn't execute it. That's when I realized the issue I had with your library was probably the same issue I was having with pandoc. I didn't think to check path however. I just assumed `cabal` was broken and so I install pandoc using `brew`

After seeing your comments I did a `cabal exec markdown-unlit` and the program was indeed executed.

Thanks

**Comment by michaelgwelch** [comment]
Yeah, go ahead and close the issue. I found a file `~/.cabal/where-is-my-stuff.txt` with the following:

> **********************************************************************
> 
> === Configuration for cabal has been written to
>     /Users/mgwelch/.cabal/config
> 
> === Executables will be installed in:
>     /Users/mgwelch/Library/Haskell/bin
> 
>     You may wish to place this on your PATH by adding the following
>     line to your ~/.bash_profile:
> 
>     export PATH="$HOME/Library/Haskell/bin:$PATH"

Sweet! After updating the path, it worked great!

**Comment by rampion** [comment]
I had this same error using new-style cabal builds, since they were only building library components of `build-depends` dependencies, and not installing their executables.

I fixed it by listing `markdown-unlit` as a `build-tool-depends` dependency, as [in the `build-tool-depends` docs](https://www.haskell.org/cabal/users-guide/developing-packages.html?highlight=build%20tool%20depends#pkg-field-build-tool-depends)

```cabal
test-suite readme
  type:           exitcode-stdio-1.0
  main-is:        README.lhs
  build-depends:  base
  build-tool-depends:  markdown-unlit:markdown-unlit
  ghc-options:    -pgmL markdown-unlit
```

I suggest updating the `README.md`
