### ISSUE TITLE
Is there a way to just use markdown-unlit by itself?

### ISSUE THREAD

**Issue by michaelgwelch** [sol/markdown-unlit#7]
I'm curious to see the output of markdown-unlit by itself.

So I'm attempting to run it like this

```
markdown-unlit -pgmL -h label myfile.lhs myfile.hs
```

Based on comments it appears that the label is just something that ghci passes in and 
that I don't need to really care what I pass for that.

The above runs without error but myfile.hs is always empty.

Am I not running it correctly? I was expecting myfile.hs to contain the "unliterate" version of the source.

**Comment by sol** [comment]
Sorry for the late response.  Please try:
```
markdown-unlit -h label myfile.lhs myfile.hs
```
